#pragma once

extern const CubieCube CubieCubeUrf1;
extern const CubieCube CubieCubeUrf2;

// 16 symmetries generated by S_F2, S_U4 and S_LR2
extern const CubieCube CubieCubeCubeSym [16];
// 18 move cubes
extern const CubieCube CubieCubeMoveCube[18];

// 组合数表 C(n,k) 用于计算组合数
extern const int32_t UtilCnk[13][13];

// UD转动与标准转动的映射表（只使用U/D面和双层转动）
extern const int32_t UtilUd2std[18]; // UD转动->标准转动
extern const int32_t UtilStd2ud[18]; // 标准转动->UD转动

// 移动有效性检查表（避免连续同轴转动）
extern const int32_t UtilCkmv2bit[11];

// 对称性相关表
extern const int32_t CubieCubeSymMult[16][16];  // 对称变换乘法表
extern const int32_t CubieCubeSymMultInv[16][16]; // 对称变换逆乘法表
extern const int32_t CubieCubeSymMove[16][18];   // 对称变换后的转动映射
extern const int32_t CubieCubeSym8Move[8 * 18];  // 8种对称下的转动映射（压缩形式）
extern const int32_t CubieCubeSymMoveUD[16][18]; // UD转动在对称变换后的映射

// URF变换转动映射（6种基准面变换）
extern const int8_t  CubieCubeUrfMove[6][18];

// 坐标转换表
extern const uint16_t CubieCubePermInvEdgeSym[2768]; // 棱块排列对称逆变换
extern const uint16_t CubieCubeFlipR2S[2048];       // Flip原始坐标->对称坐标
extern const uint16_t CubieCubeTwistR2S[2187];      // Twist原始坐标->对称坐标
extern const uint16_t CubieCubeEPermR2S[40320];     // 棱块排列原始坐标->对称坐标
extern const int8_t  CubieCubePerm2CombP[2768];     // 角块排列->组合坐标
extern const int8_t  CubieCubeMPermInv[24];         // 中棱块排列逆变换

// 移动表（状态转移）
extern const uint16_t CoordCubeUDSliceMove[495][18];  // UDSlice坐标移动表
extern const uint16_t CoordCubeTwistMove[324][18];    // Twist坐标移动表
extern const uint16_t CoordCubeFlipMove[336][18];     // Flip坐标移动表
extern const uint16_t CoordCubeUDSliceConj[495][8];   // UDSlice对称共轭
extern const int32_t CoordCubeUDSliceTwistPrun[20048];   // 角块排列移动表（UD转动）
extern const int32_t CoordCubeUDSliceFlipPrun[20791];   // 棱块排列移动表（UD转动）
extern const uint16_t CoordCubeCPermMove[2768][10];     // 中棱块排列移动表（UD转动）
extern const uint16_t CoordCubeEPermMove[2768][10];     // 中棱块对称共轭
extern const uint16_t CoordCubeMPermMove[24][10];   // 角块组合对称共轭

// 剪枝表（加速搜索）
extern const uint16_t CoordCubeMPermConj[24][16];    // UDSlice+Twist剪枝
extern const uint16_t CoordCubeCCombPConj[140][16];     // UDSlice+Flip剪枝
extern const int32_t CoordCubeMCPermPrun[8305];           // 中棱+角块排列剪枝
extern const int32_t CoordCubeEPermCCombPPrun[48441];     // 棱块排列+角块组合剪枝
extern const uint16_t CubieCubeFlipS2RF[2688];            // Flip对称坐标转换
extern const int32_t CoordCubeTwistFlipPrun[82945];       // Twist+Flip组合剪枝
